### ISSUE TITLE
请问如何获取cookie

### ISSUE THREAD

**Issue by Xander-C** [FishZe/WXWork-HealthReport#1]
尝试对电脑手机客户端进行抓包，都无法获取cookie。客户端的ssl证书应该是内置的，系统安装了抓包软件的证书并不能解包

**Comment by FishZe** [comment]
请问您用的是什么抓包软件呢？

**Comment by FishZe** [comment]
这边需要抓一个`https://work.weixin.qq.com/healthreport/`请求的包，由于是https的，因此需要抓包软件安装一下证书

**Comment by FishZe** [comment]
<img width="1280" alt="2022-12-01" src="https://user-images.githubusercontent.com/65108397/205012307-a38730b7-4895-416d-a526-afb202b5d8a9.png">

**Comment by Xander-C** [comment]
换charles抓到了，估计bp太老了，之前用的bp抓的。感谢

**Comment by FishZe** [comment]
:smile:
